# Generated by Django 5.0 on 2024-01-11 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apk", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="data",
        ),
    ]
